# Generated by Django 4.2.7 on 2023-12-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calories", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("servings", models.IntegerField()),
                ("ingredients", models.TextField(blank=True)),
                ("recipe", models.TextField(blank=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_breakfast", models.BooleanField(default=False)),
                ("is_lunch", models.BooleanField(default=False)),
                ("is_dinner", models.BooleanField(default=False)),
                ("is_snack", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
