# Generated by Django 4.2.7 on 2023-12-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_planner", "0003_alter_ingredient_id_alter_ingredient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredient_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
