# Generated by Django 4.2.7 on 2023-12-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_planner", "0004_recipe_ingredient_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
